### ISSUE TITLE
When the code will be released?

### ISSUE THREAD

**Issue by JunMa11** [trypag/NonAdjLoss#1]
Hi, thanks for your sharing.

When the code will be released?

Looking forward to your reply!

Best,
Edward

**Comment by trypag** [comment]
Hi Edward,
Sorry I missed your issue. We are currently extending the original work, I think the final version should be ready by the end of november. I will make sure to notify you.
Best
Pierre-Antoine

**Comment by JunMa11** [comment]
Get it. Thanks for your reply very much.

**Comment by xmengli** [comment]
Hi, When the code will be released?

**Comment by trypag** [comment]
Hi, it should be out by the beginning of January, the article version is under redaction.

**Comment by tkepp** [comment]
Hey, are there any updates regarding the release of the code?

**Comment by trypag** [comment]
Hi @tkepp, I am currently working on it, it will be done by the end of the week. This repository will host the basic code, graph extraction from data, NonAdjLoss and a function to control the lambda parameter. I will soon open source a more general library for medical imaging with torch, composed of image readers, datasets and patch sampler.

**Comment by trypag** [comment]
By default it will require torch v1.0, but it can work with a lower version by commenting the code

**Comment by tkepp** [comment]
That sounds great! I am very excited. Thanks for the fast response.

**Comment by trypag** [comment]
I will be happy to help you get everything to work next week.

**Comment by trypag** [comment]
The code is ready but I have spotted a memory leak issue during testing, I am trying to fix it right now.

**Comment by trypag** [comment]
The code is out. There is a dependency to a library that I will be open-sourcing tomorrow. This library includes an example implementation of NonAdjLoss for the MICCAI 2012 brain segmentation challenge. I will post a last message here when it will be done.

**Comment by trypag** [comment]
The library is out https://github.com/trypag/torchmed
You will find an example application of the NonAdjLoss [here](https://github.com/trypag/torchmed/tree/master/examples/02_segmentation_NonAdjLoss).
Feel free to ask questions.
