### ISSUE TITLE
3D NonAdjLoss

### ISSUE THREAD

**Issue by JunMa11** [trypag/NonAdjLoss#2]
Thanks for sharing the great work.

Can the proposed loss be extended to 3D segmentation?

Best,
Jun

**Comment by trypag** [comment]
Hi, yes the loss can be extended to 3D segmentation without much effort. Though the GPU memory requirement will be increasing.

**Comment by trypag** [comment]
Once you have extracted the ground truth adjacency matrix from your segmentation maps, I can provide some help for the 3D Loss.

**Comment by JunMa11** [comment]
Got it, thanks for your reply very much. I will try to do that.
