### ISSUE TITLE
Organ Segmentation - Small Number of Classes and Background Class?

### ISSUE THREAD

**Issue by aksg87** [trypag/NonAdjLoss#4]
Thank you so much for sharing this exciting approach. I also found the paper very interesting!

Question - Does this method work for situations where you are only predicting a few classes? For example, the right and left kidney? If so, in this situation, is it advisable to make the background a third class (i.e., nb_labels = 3)? From my understanding, the adjacency matrix in the paper is learning a prior based on the complex set of relations across the multiple brain structures. Hence, I wasn't sure if this would apply to problems with a few classes. I appreciate any clarifications on this.

**Comment by trypag** [comment]
Hey @aksg87 

Thank you for the feedback ! 
It's a good question, the short answer is no, you will probably not see a big improvement if you have a limited number of labels. To evaluate the potential of this method on your problem, you should first try to evaluate if your current best segmentation model has any inconsistencies, like predicting heart in the middle of the right kidney.
You seem to know the anatomy of the body pretty well, as an expert you could build the adjacency matrix by yourself and then evaluate the adjacency matrix of your segmentation model to compare them with your ground truth.

The first thing I can advise is to find out how much abnormal your current model can be. Then, even if your problem has a nice potential, you will likely not see big improvements on dice, but much more on anomaly metrics like surface distance or hausdorff distance. Also the segmentations will look much more normal to experts.

**Comment by aksg87** [comment]
Thanks! That makes a lot of sense. I appreciate the clarifications and suggestions @trypag
